kind = "DojoModel"
class_hash = "0x758c4c78b0a5bc26701ca0d5c8d5e3783eb6a3ea2e6eea30044c1fd7fbe0b3e"
original_class_hash = "0x758c4c78b0a5bc26701ca0d5c8d5e3783eb6a3ea2e6eea30044c1fd7fbe0b3e"
abi = "manifests/dev/base/abis/models/starkludo-Game-5286f583.json"
tag = "starkludo-Game"
manifest_name = "starkludo-Game-5286f583"

[[members]]
name = "id"
type = "u64"
key = true

[[members]]
name = "created_by"
type = "ContractAddress"
key = false

[[members]]
name = "game_status"
type = "GameStatus"
key = false

[[members]]
name = "game_mode"
type = "GameMode"
key = false

[[members]]
name = "player_green"
type = "ContractAddress"
key = false

[[members]]
name = "player_yellow"
type = "ContractAddress"
key = false

[[members]]
name = "player_blue"
type = "ContractAddress"
key = false

[[members]]
name = "player_red"
type = "ContractAddress"
key = false

[[members]]
name = "winner"
type = "ContractAddress"
key = false

[[members]]
name = "next_player"
type = "ContractAddress"
key = false

[[members]]
name = "rolls_count"
type = "u256"
key = false

[[members]]
name = "rolls_times"
type = "u256"
key = false
