kind = "DojoModel"
class_hash = "0x89ac84c2d5ef822377403b45d969e65372ed2db306d238baa6aac0b429edb1"
original_class_hash = "0x89ac84c2d5ef822377403b45d969e65372ed2db306d238baa6aac0b429edb1"
abi = "manifests/dev/base/abis/models/starkludo-Moved-1933e376.json"
tag = "starkludo-Moved"
manifest_name = "starkludo-Moved-1933e376"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "direction"
type = "Direction"
key = false
