kind = "DojoModel"
class_hash = "0x293be90c6dd0682f909cc924db9ad07035f79150793473b0929bdc92cf6a582"
original_class_hash = "0x293be90c6dd0682f909cc924db9ad07035f79150793473b0929bdc92cf6a582"
abi = "manifests/dev/base/abis/models/starkludo-Moves-1c65cfcb.json"
tag = "starkludo-Moves"
manifest_name = "starkludo-Moves-1c65cfcb"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "remaining"
type = "u8"
key = false

[[members]]
name = "last_direction"
type = "Direction"
key = false

[[members]]
name = "can_move"
type = "bool"
key = false
